spring:
  profiles:
    active: local # Activate "local" profile by default
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/master.yml
  kafka:
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
application:
  kafka:
    topic: products
    partitions: 2
    # In production, this config should be equal to the number of Kafka brokers.
    replicationFactor: 1
